---
title: "Codes_for_NatCom_Article"
output: html_document
---

#####
##### Packages to install
#####

```{r}
library(dplyr)
library(tidyr)
library(reshape2)
library(reshape)
library("gridExtra")
library("cowplot")
require(readxl)
require(ggplot2)
require(gplots)
require(R.matlab)
require(modeest)
require(abind)
require(nlme)
require(multcomp)
require(dunn.test)
require(ggpurb)
library(onewaytests)
library(userfriendlyscience)
require(lawstat)
require(car)
require(rstatix)
require(lme4)
require("writexl")
require("readxl")
require("ggplot2")
```



#####
##### AIM Analysis - Figure 1
#####

```{r}
df_AIM = read_xlsx("df_AIMs.xlsx")

## Oral


myColors <- c("#676767", "#CD458F", "#96C121", "#3CA7DF")
names(myColors) <- levels(factor(df_hist$Condition_merged))
colScale <- scale_colour_manual(name = "Condition_merged",values = myColors)

df_AIM$Condition_merged <- factor(df_AIM$Condition_merged,
    levels = c("SHAM", "PD", "PD_CORR", "PD_PREV"),ordered = TRUE)
  
df_oral = aggregate(value_oral~Week*Condition_merged*mouse, data = df_AIM, FUN=function(x) sum(x))
  
df_oral$Week <- factor(df_oral$Week,
                      levels = c("4", "5", "6", "7", "8", "9"),ordered = TRUE)


p <- ggplot(data=df_oral, aes(x = Condition_merged, y = value_oral, Fill = Week, color = Condition_merged)) +
    geom_boxplot(aes(middle  = mean(value_oral)), width = .9, position = position_dodge2(padding=.7, width=0.7)) +
    theme_classic()+
    # stat_summary(fun.data = n_fun, geom = "text", 
    #        aes(group=Condition_merged),
    #        hjust = 0.75, position = position_dodge(1)) +
    theme(legend.position = "none",
          axis.text.x = element_text(size = 18, angle = 0, hjust = .5, vjust = .5, face = "plain"),
          axis.text.y = element_text(size = 18),
          axis.title.x = element_text(size = 20, angle = 0, hjust = .5, vjust = 0, face = "plain"),
          axis.title.y = element_text(size = 20, angle = 90, hjust = .5, vjust = .5, face = "plain"))+
    scale_x_discrete(labels = c('SHAM','LID','LID_CORR', "LID_PREV"))+
    ylim(0,22)+
    colScale +
    labs(x="Weeks", y = "Total oral AIMs score")

plot(p)

#ggsave("Oraltot_Fig1_V5_BP2.pdf", p, useDingbats= F, height = 7 , width = 4 * aspect_ratio)

#write_xlsx(df_oral,"C:/Users/berenice/Documents/Src/Bérénice/Figure1e.xlsx")

## Axial 

df_axial = aggregate(value_axial~Week*Condition_merged*mouse, data = df_AIM, FUN=function(x) sum(x))


df_axial$Week <- factor(df_axial$Week,
                        levels = c("4", "5", "6", "7", "8", "9"),ordered = TRUE)


p_axial <- ggplot(data=df_axial,aes(x = Condition_merged, y = value_axial, Fill = Week, color = Condition_merged)) +
  geom_boxplot(aes(middle  = mean(value_axial)), width = .9, position = position_dodge2(padding=.7, width=0.7)) +
  theme_classic()+
  theme(legend.position = "none",
        axis.text.x = element_text(size = 18, angle = 0, hjust = .5, vjust = .5, face = "plain"),
        axis.text.y = element_text(size = 18),
        axis.title.x = element_text(size = 20, angle = 0, hjust = .5, vjust = 0, face = "plain"),
        axis.title.y = element_text(size = 20, angle = 90, hjust = .5, vjust = .5, face = "plain"))+
  colScale +
  scale_x_discrete(labels = c('SHAM','LID','LID_CORR', "LID_PREV"))+
  ylim(0,18)+
  labs(x="Weeks", y = "Total axial AIMs score")


plot(p_axial)

#ggsave("Axialtot_Fig1_V5_BP2.pdf", p_axial, useDingbats= F, height = 7 , width = 4 * aspect_ratio)

#write_xlsx(df_axial,"C:/Users/berenice/Documents/Src/Bérénice/Figure1f.xlsx")

##Limb

df_limb = aggregate(value_limb~Week*Condition_merged*mouse, data = df_AIM, FUN=function(x) sum(x))

df_limb$Week <- factor(df_limb$Week,
                       levels = c("4", "5", "6", "7", "8", "9"),ordered = TRUE)


p_limb <- ggplot(data=df_limb, aes(x = Condition_merged, y = value_limb, Fill = Week, color = Condition_merged)) +
  geom_boxplot(aes(middle  = mean(value_limb)), width = .9, position = position_dodge2(padding=.7, width=0.7)) +
  theme_classic()+
  theme(legend.position = "none",
        axis.text.x = element_text(size = 18, angle = 0, hjust = .5, vjust = .5, face = "plain"),
        axis.text.y = element_text(size = 18),
        axis.title.x = element_text(size = 20, angle = 0, hjust = .5, vjust = 0, face = "plain"),
        axis.title.y = element_text(size = 20, angle = 90, hjust = .5, vjust = .5, face = "plain"))+
  colScale +
  ylim(0,15)+
  scale_x_discrete(labels = c('SHAM','LID','LID_CORR', "LID_PREV"))+
  labs(x="Weeks", y = "Total limb AIMs score")

plot(p_limb)


#ggsave("Limbtot_Fig1_V5_BP2.pdf", p_limb, useDingbats= F, height = 7 , width = 4 * #aspect_ratio)

#write_xlsx(df_limb,"C:/Users/berenice/Documents/Src/Bérénice/Figure1g.xlsx")

## Statisics 




```


#####
##### TH analysis
#####


```{r}
#####
##### TH Analysis
#####

n_fun <- function(x){
  return(c(y = median(x)*1.05,label = length(x)))
}

df_TH = read.csv2(file = "C:/Users/berenice/Documents/Src/Bérénice/df_TH.csv")

myColors <- c("#676767", "#CD458F", "#96C121", "#3CA7DF")
names(myColors) <- levels(factor(df_hist$Condition_merged))
colScale <- scale_colour_manual(name = "Condition_merged",labels = c("SHAM", "LID", "LID_CORR", "LID_PREV"),values = myColors)

legend_title <- "Condition"
df_TH$Condition_merged <- factor(df_TH$Condition_merged,
                                   levels = c("SHAM", "PD", "PD_CORR", "PD_PREV"),ordered = TRUE)

##### 
##### All mice - Figure 1c
#####


p <- ggplot(df_TH, aes(x = Condition_merged, y = Perte, color = Condition_merged)) +
  geom_boxplot(width=0.5,aes(middle  = mean(Perte))) +
  theme_classic() +
  theme(legend.position = "none",
        legend.text = element_text(size=18),
        axis.text.x = element_text(size = 22, angle = 0, hjust = .5, vjust = .5, face = "plain"),
        axis.text.y = element_text(size = 22),  
        axis.title.x = element_text(size = 25, angle = 0, hjust = .5, vjust = 0, face = "plain"),
        axis.title.y = element_text(size = 25, angle = 90, hjust = .5, vjust = .5, face = "plain"))+
  colScale+
  scale_x_discrete(labels = c('SHAM','LID','LID_CORR', "LID_PREV"))+
  labs(x="Lesion", y = "Loss of striatal \n tyrosine-hydroxylase positive fibers (%)",
       title = "All mice")
print(p)

aspect_ratio <- 2.5
height <- 7

#ggsave("Quantif_TH.pdf", p, height = 10 , width = 3 * aspect_ratio)

#write_xlsx(df_limb,"C:/Users/berenice/Documents/Src/Bérénice/Figure1g.xlsx")


##### 
##### DCN mice - Figure Supp 6c
#####

df_TH_DCN = subset(df_TH, Student == "B" & Condition_merged != "PD_CORR")

p <- ggplot(df_TH_DCN, aes(x = Condition_merged, y = Perte, color = Condition_merged)) +
  geom_boxplot(width=0.5,aes(middle  = mean(Perte))) +
  theme_classic() +
  theme(legend.position = "none",
        legend.text = element_text(size=18),
        axis.text.x = element_text(size = 22, angle = 0, hjust = .5, vjust = .5, face = "plain"),
        axis.text.y = element_text(size = 22),  
        axis.title.x = element_text(size = 25, angle = 0, hjust = .5, vjust = 0, face = "plain"),
        axis.title.y = element_text(size = 25, angle = 90, hjust = .5, vjust = .5, face = "plain"))+
  colScale+
  labs(x="Lesion", y = "Loss of striatal \n tyrosine-hydroxylase positive fibers (%)",
       title = "All mice")
print(p)

aspect_ratio <- 2.5
height <- 7

#ggsave("Quantif_TH_FosB.pdf", p, height = 10 , width = 3 * aspect_ratio)

write_xlsx(df_TH,"C:/Users/berenice/Documents/Src/Bérénice/Figure1c.xlsx")


##### 
##### Stats TH 
#####

df_TH$Condition_merged = as.factor(df_TH$Condition_merged)


l = leveneTest(Perte~Condition_merged, data = na.omit(subset(df_TH, Student == "B")))
l$`Pr(>F)`

res.aov = aov(Perte~Condition_merged, data = na.omit(subset(df_TH, Student == "B")))
summary(res.aov)
TukeyHSD(res.aov)
```



#####
##### Code for BP - DCN 
#####


```{r}

myColors <- c("#676767", "#CD458F", "#96C121", "#3CA7DF")
names(myColors) <- levels(factor(df_hist$Condition_merged))
colScale <- scale_colour_manual(name = "Condition_merged",values = myColors)

df = df_all_s053 %>% 
  filter(block == 3 & Phase == "Pre-LDOPA" | block == 7 & Phase == "Post-LDOPA") %>% 
  filter(Week_cat5 != "W1") %>% 
  #filter(Condition %in% c("SHAM", "PD", "PD_CORR", "PD_PREV")) %>% 
  filter(Condition %in% c("SHAM", "PD", "PD_PREV")) %>% 
  filter(quality <= 2) %>% 
  dplyr::select("Week2", "mouse", "Condition", "Condition_merged", "region2", "region","name", "cell", "rate", "cv.isi", "cv2.isi", "quality","Week", "mouse", "cell", "Week_cat", "Week_cat3", "Week_cat4", "Week_cat5", "b.rate", "b.rate.on", "b.rate.off")

par2 = list("rate", "cv.isi", "cv2.isi")

BP_subset = function (df, par=par2[[i]]) {
  df2 = data.frame(Condition = df$Condition_merged,
                   mouse = df$mouse,
                   Phase = df$Week_cat5,
                   Rate = df[[par]], 
                   region2 = df$region2)
}

df2 = data.frame(Condition = df$Condition_merged,
                 Phase = df$Week_cat5,
                 mouse = df$mouse,
                 Rate = df$cv.isi, 
                 region2 = df$region2)
g=list()

for(reg in unique(df2$region2)) {
  g[[reg]]  <- ggplot(subset(df2, region2 == reg), aes(x = Condition, y = Rate, fill = Phase, color = Condition)) +
    geom_boxplot(aes(middle  = median(Rate), color = Condition), width = .6, position = position_dodge2(padding=.7, width=0.7)) +
    theme_classic() +
    theme(legend.position="none",
          plot.title = element_text(size=20, hjust = 0.5),
          axis.text.x = element_text(size = 18, angle = 0, hjust = .9, vjust = .9, face = "plain"),
          axis.text.y = element_text(size = 18),  
          axis.title.x = element_text(size = 20, angle = 0, hjust = .5, vjust = 0, face = "plain"),
          axis.title.y = element_text(size = 20, angle = 90, hjust = .5, vjust = .5, face = "plain"))+
    #theme(legend.position="none",
    #      title=element_text(hjust = 0.5)) +
    #scale_y_log10(limits = c(0.45, 1.2)) + 
    #scale_y_log10()+ 
    #scale_y_log10(limits = c(0.5, 100)) + 
    ylim(0,1.3)+
    colScale+
    scale_fill_manual(values=c("#FFFFFF", "#FFFFFF", "#FFFFFF", "#FFFFFF"))+
    scale_x_discrete(labels = c('SHAM','LID',"LID_PREV"))+
    labs(title= paste(print(reg)), 
         x="Condition", y = "Firing rate")
}


f = do.call(grid.arrange,c(g, ncol=3))
#f2 = f[c("IN", "DN", "FN")]
plot(f)

#ggsave("df_all_s053_cv.isi_BP.pdf", g, useDingbats= F, height = 7 , width = 4 * aspect_ratio)

write_xlsx(df2,"C:/Users/berenice/Documents/Src/Bérénice/FigSupp6i,j,k.xlsx")


### Test de levene - variance

df_stat = df
df_stat$log.rate = log(df$rate)
df_stat = df_stat %>%  filter(Condition %in% c("SHAM", "PD", "PD_CORR", "PD_PREV"))
df_stat$Condition <- factor(df_stat$Condition, levels = c("SHAM", "PD", "PD_CORR", "PD_PREV"),ordered = TRUE)
df_stat$Week_cat5 <- factor(df_stat$Week_cat5, levels = c("W1", "W2-W3", "W4-W5", "W6-W7", "W8-W9"),ordered = TRUE)

g1_levene = list()
g2_levene = list()

for (reg in unique(df_stat$region)) {
  for (cond in unique(df_stat$Condition_merged)) {
  s = subset(df_stat, region == reg & Condition_merged == cond)
  s2 = s %>% filter(Week_cat5 != "W1")
  s2$Week_cat5 = droplevels(s2$Week_cat5)
  s2$Condition_merged = droplevels(s2$Condition_merged)
  l = leveneTest(cv.isi~Week_cat5, data = na.omit(s2))
  #l = leveneTest(b.rate.off~Week_cat5, data = na.omit(s2))
  g1_levene[[cond]] = l$`Pr(>F)`
  #print(paste(reg,cond, l$`Pr(>F)`))
  }
g2_levene[[reg]] = g1_levene
  }

g3_anova = list()
g3_welch = list()
g4_anova =list()
g4_welch =list()

for (reg in unique(df_stat$region)) {
  for (cond in unique(df_stat$Condition)) {
    s = subset(df_stat, region == reg & Condition == cond)
    s2 = s %>% filter(Week_cat5 != "W1") %>% dplyr::select ("Condition", "Week_cat5", "cv2.isi", "cv.isi", "log.rate", "b.rate.off")
    s2 = na.omit(s2)
    s2$Week_cat5 = droplevels(s2$Week_cat5)
    s2$Condition = droplevels(s2$Condition)
    print(cond)
    
    if (g2_levene[[reg]][[cond]][[1]] > 0.05) {
      res.avo = aov(cv.isi~Week_cat5, data = na.omit(s2))
      #res.avo = aov(b.rate.off~Week_cat5, data = na.omit(s2))
      summary(res.avo)
      g3_anova[[cond]] = TukeyHSD(res.avo)
      #$Week_cat5[,4]
      paste(print(reg), print(cond))
   
       } else {
      welch_res = welch.test(cv.isi~Week_cat5, data=na.omit(s2))
      #p = posthocTGH(s2$log.rate, s2$Week_cat5, method="games-howell", conf.level = 0.95, digits=5)
      #welch_res = welch.test(b.rate.off~Week_cat5, data=na.omit(s2))
      #p = posthocTGH(s2$b.rate.off, s2$Week_cat5, method="games-howell", conf.level = 0.95, digits=5)
      p = games_howell_test(s2, cv.isi~Week_cat5, conf.level = 0.95, detailed = FALSE)
      g3_welch[[cond]] = p$output$games.howell
  }
  }
  g4_anova[[reg]] = g3_anova
  g4_welch[[reg]] = g3_welch
}

#g4_anova[[1]][[1]]$Week_cat5[,4]

#write.table(g4_anova,"test.csv",sep=";")


df= data.frame(x = 1:6)
for (i in 1:length (g4_anova)) {
  for (j in 1:length (g4_anova[[i]])) {
    res = as.data.frame(g4_anova[[i]][[j]]$Week_cat5[,4])
    colnames(res)[1] = paste0(names(g4_anova[i][[1]][j]), '_', names(g4_anova[i]))
    df = cbind(df, res)
  }
}

write.table(df,"DCN_anova.csv",sep=";")

#### Mean + n 

m=list()
nb=list()
m2=list()
nb2=list()
m3=list()
nb3=list()
nb_mouse=list()
nb_mouse2=list()
nb_mouse3=list()

for (reg in unique(df_stat$region)) {
  for (cond in unique(df_stat$Condition)) {
    for (w in unique(df_stat$Week_cat5)) {
      s = df_stat %>% filter(Week_cat5 != "W1") 
      s2 = subset(s, region == reg & Condition == cond & Week_cat5 == w)
      #s2=na.omit(s2)
      m[[w]] = mean(s2$rate)
      paste(print(w), print(cond), print(reg))
      nb[[w]] = length(s2$name)
      nb_mouse[[w]] = length(unique(s2$mouse))
    }
    m2[[cond]] = m
    nb2[[cond]] = nb
    nb_mouse2[[cond]] = nb_mouse
  }
  m3[[reg]] = m2
  nb3[[reg]] = nb2
  nb_mouse3[[reg]] = nb_mouse2
}
```


######
###### Data M1, PF, VAL
###### 

# Rate

```{r}
load("C:/Users/berenice/Documents/Src/Bérénice/all_Adele.RData")

myColors <- c("#676767", "#CD458F", "#96C121", "#3CA7DF")
names(myColors) <- levels(factor(df_hist$Condition_merged))
colScale <- scale_colour_manual(name = "Condition_merged",labels = c("SHAM", "LID", "LID_CORR", "LID_PREV"),values = myColors)

df = allstats2 %>% dplyr::select("region", "Phase", "protocol", "rank", "Condition_merged", "name", "cell", "rate", "cv.isi", "cv2.isi", "quality", "stim100ms", "Week", "mouse", "cell", "Week_cat5")

df2 = df %>%
  filter(quality <= 2) %>% 
  filter(protocol == "OFpretb" & stim100ms == "y") %>% 
  filter(Condition_merged %in% c("SHAM", "PD", "PD_PREV")) %>% 
  filter(Week_cat5 != "W1") %>% 
  filter(rank == "1")


df3 = data.frame(Condition = df2$Condition_merged,
                 Phase = df2$Week_cat5,
                 Rate = df2$rate,
                 Region = df2$region)
g = list()

for(reg in c("M1", "PF", "VAL")) {
  g[[reg]]  <- ggplot(subset(df3, Region == reg), aes(x = Condition, y = Rate, fill = Phase)) +
  geom_boxplot(aes(middle  = mean(Rate), color = Condition), width = .7, position = position_dodge2(padding=.7, width=0.7)) +
  theme_classic() +
  theme(legend.position = "none")+
  colScale+
  scale_x_discrete(labels = c("SHAM","LID","LID_PREV"))+
  scale_fill_manual(values=c("#FFFFFF", "#FFFFFF", "#FFFFFF", "#FFFFFF"))+
  scale_y_log10(limits = c(0.1, 7.5)) +
  #ylim(0,2)+
  #ylim(0.1, 7.5)+  
  labs(title= paste(print(reg)), 
           x="Condition", y = "Firing Rate (Hz)")
  }

f = do.call(grid.arrange,c(g, ncol=3))
plot(f)

#ggsave("M1-PF-VAL_cv_BP.pdf", f, useDingbats= F, height = 6 , width = 4 * aspect_ratio)

write_xlsx(df3,"C:/Users/berenice/Documents/Src/Bérénice/Figure3c,d.xlsx")

```


```{r}

### Statistics for M1, PF, and VAL - Figure 3 and Fig.Supp10. 

par = c(df_stat$log(rate), df_stat$cv.isi, df_stat$cv2.isi)

df_stat = df2
df_stat$Week_cat5 = as.factor(df_stat$Week_cat5)
df_stat$Week_cat5 = droplevels(df_stat$Week_cat5)

s = list()
for (cond in c('PD', 'SHAM', 'PD_PREV')) {
l = lme(cv.isi~Week_cat5, random=~1|mouse/Week_cat5, data=subset(na.omit(df_stat), region == "PF" & Condition_merged == cond))
print(anova(l))
}
```


# cv.isi

```{r}

df3 = data.frame(Condition = df2$Condition_merged,
                 Phase = df2$Week_cat5,
                 Rate = df2$cv.isi,
                 Region = df2$region)
g = list()

for(reg in c("M1", "PF", "VAL")) {
  g[[reg]]  <- ggplot(subset(df3, Region == reg), aes(x = Condition, y = Rate, fill = Phase)) +
  geom_boxplot(aes(middle  = mean(Rate), color = Condition), width = .7, position = position_dodge2(padding=.7, width=0.7)) +
  theme_classic() +
  theme(legend.position = "none")+
  colScale+
  scale_x_discrete(labels = c("SHAM","LID", "LID_PREV"))+
  scale_fill_manual(values=c("#FFFFFF", "#FFFFFF", "#FFFFFF", "#FFFFFF"))+
  scale_y_log10(limits = c(0.1, 7.5)) +
  #ylim(0,2)+
  #ylim(0.1, 7.5)+  
  labs(title= paste(print(reg)), 
           x="Condition", y = "cv.isi")
  }

f = do.call(grid.arrange,c(g, ncol=3))
plot(f)

#ggsave("M1-PF-VAL_cv_BP.pdf", f, useDingbats= F, height = 6 , width = 4 * aspect_ratio)

write_xlsx(df3,"C:/Users/berenice/Documents/Src/Bérénice/FigureSupp10e.xlsx")

```

# cv2.isi 

```{r}
df3 = data.frame(Condition = df2$Condition_merged,
                 Phase = df2$Week_cat5,
                 Rate = df2$cv2.isi,
                 Region = df2$region)
g = list()

for(reg in c("M1", "PF", "VAL")) {
  g[[reg]]  <- ggplot(subset(df3, Region == reg), aes(x = Condition, y = Rate, fill = Phase)) +
  geom_boxplot(aes(middle  = mean(Rate), color = Condition), width = .7, position = position_dodge2(padding=.7, width=0.7)) +
  theme_classic() +
  theme(legend.position = "none")+
  colScale+
  scale_x_discrete(labels = c("SHAM","LID", "LID_PREV"))+
  scale_fill_manual(values=c("#FFFFFF", "#FFFFFF", "#FFFFFF", "#FFFFFF"))+
  ylim(0,2)+
  labs(title= paste(print(reg)), 
           x="Condition", y = "cv2.isi")
  }

f = do.call(grid.arrange,c(g, ncol=3))
plot(f)

#ggsave("M1-PF-VAL_cv_BP.pdf", f, useDingbats= F, height = 6 , width = 4 * aspect_ratio)

write_xlsx(df3,"C:/Users/berenice/Documents/Src/Bérénice/FigureSupp10f.xlsx")

```


#####
##### Figure 5e - CNO distrib counting
#####

```{r}
count_dreadd = read_xlsx("C:/Users/berenice/Desktop/Fichiers_Analyse_Comportement_histo_AIM_decembre2019/Résultat comptage cellules DREADD béré.xlsx")

df=as.data.frame(matrix(ncol=1, nrow=2))

ratio_tot = sum(subset(count_dreadd, Treatment != "none")$nb_mCherry) / sum(subset(count_dreadd, Treatment != "none")$nb_cells) * 100

df$cells_dreadds = c(ratio_tot, 100-ratio_tot)

g <- ggplot(df, aes(x = "", y = cells_dreadds, fill = group)) +
  geom_col(color="black") +
  geom_text(aes(label = round(cells_dreadds, digits = 2)),
            size=8,
            position = position_stack(vjust = 0.5)) +
  coord_polar(theta = "y") +
  theme_void()+
  guides(fill = guide_legend(title = "% of cells"))+
  scale_fill_manual(values = c("#E20019", "#3CA7DA"), labels = c("Cells expressing
DREADDs", "Other cells"))

plot(g)

write_xlsx(df,"C:/Users/berenice/Documents/Src/Bérénice/Figure5e-top.xlsx")

#ggsave("Pct_DREADDsonly.pdf", g, height = 4 , width = 3 * aspect_ratio)


### Distribution of CTL and DREADDs

count_dreadd$Treatment = factor(count_dreadd$Treatment, 
                                levels = c("none", "saline", "CNO"), ordered = T)

g <- ggplot(count_dreadd, aes(x = Treatment, y = Ratio, fill = Treatment)) +
  geom_boxplot(width = .4, position = position_dodge2(padding=.7, width=0.7))+
  geom_point(shape="circle", size=3, color="grey")+
  theme_classic()+
  scale_fill_manual(values = c("#676767","#79A4D3", "#2F4B97"))+
  ylim(0,50)

plot(g)  

write_xlsx(count_dreadd,"C:/Users/berenice/Documents/Src/Bérénice/Figure5e-bottom.xlsx")

#ggsave("Pct_DREADDs_BP-3.pdf", g, useDingbats= F, height = 5 , width = 2 * aspect_ratio)


```



#####
##### Figure 5f - CNO
#####

```{r}

df_AIM_cno = read_xlsx("df_AIM_CNO.xlsx")

## Oral

df_oral_cno = df_AIM_cno %>% 
  filter (mouse != "s069") %>% 
  dplyr::select ("mouse", "Condition_merged", "Week", "value_oral", "Treatment", "time") %>% 
  #filter(time == '20' | time == '40') %>% 
  filter(time == '40') %>% 
  filter(Week %in% c("4", "5", "6", "7"))

df_oral = aggregate(value_oral~Treatment*mouse*time, data = df_oral_cno, FUN=function(x) sum(x))

df_oral$Treatment<- as.factor(df_oral$Treatment)

df_oral$Treatment<- factor(df_oral$Treatment,
                      levels = c("saline", "CNO"),ordered = TRUE)


p <- ggplot(data=df_oral, aes(x = Treatment, y = value_oral, fill = Treatment, color = Treatment)) +
  geom_boxplot(aes(middle  = mean(value_oral)), width = .2, position = position_dodge2(padding=.7, width=0.7)) +
  theme_classic()+
  theme(legend.position = "none",
        axis.text.x = element_text(size = 18, angle = 0, hjust = .5, vjust = .5, face = "plain"),
        axis.text.y = element_text(size = 18),
        axis.title.x = element_text(size = 20, angle = 0, hjust = .5, vjust = 0, face = "plain"),
        axis.title.y = element_text(size = 20, angle = 90, hjust = .5, vjust = .5, face = "plain"))+
  ylim(0,15)+
  scale_color_manual(name = "Clarity", values = c("#0062FF", "#3737D1"))+
  scale_fill_manual(name= "Clarity", values = c("#FFFFFF", "#FFFFFF"))+
  labs(x="Treatment", y = "Oral AIMs score post-stimulations")

plot(p)

#ggsave("CNO_OralAIM_B3_Fig-2.pdf", p, useDingbats= F, height = 7 , width = 3 * aspect_ratio)

write_xlsx(df_oral,"C:/Users/berenice/Documents/Src/Bérénice/Figure5f.xlsx")

```


#####
##### Figure7 - FosB
#####


```{r}

df_FosB = read.csv2("C:/Users/berenice/Documents/Src/Bérénice/df_FosB.csv")

df_FosB$Condition_merged <- factor(df_FosB$Condition_merged,
    levels = c("SHAM", "PD", "PD_CORR", "PD_PREV"),ordered = TRUE)

myColors <- c("#676767", "#CD458F", "#96C121", "#3CA7DF")
names(myColors) <- levels(factor(df_hist$Condition_merged))
colScale <- scale_colour_manual(name = "Condition_merged",values = myColors)

g <- ggplot(data=df_FosB, aes(x = Condition_merged, y = Lesioned.vs.unlesioned, Fill = Condition_merged, color = Condition_merged)) +
    geom_boxplot(aes(middle  = mean(Lesioned.vs.unlesioned), color = Condition_merged)) +
    stat_boxplot(geom ='errorbar', width = 0.15)+
    theme_classic()+
    theme(legend.position = "none",
          axis.text.x = element_text(size = 16, angle = 0, hjust = .5, vjust = .5, face = "plain"),
          axis.text.y = element_text(size = 16),
          axis.title.x = element_text(size = 18, angle = 0, hjust = .5, vjust = 0, face = "plain"),
          axis.title.y = element_text(size = 18, angle = 90, hjust = .5, vjust = .5, face = "plain"))+
    colScale +
    labs(x="Condition", y = "Number cells expressing FosB 
(ipsi- vs contralateral sides) in%")


plot(g)

write_xlsx(df_FosB,"C:/Users/berenice/Documents/Src/Bérénice/Figure7.xlsx")


```


#####
##### Figures Supp 1b, 2, and 3 - 3 AIMs in details - BP
#####

```{r}
df_AIM$time <- factor(df_AIM$time,
                      levels = c("-20", "0", "20", "40", "60", "80", "100", "120"),ordered = TRUE)

df_AIM$Condition_merged <- factor(df_AIM$Condition_merged,
                      levels = c("SHAM", "PD", "PD_CORR", "PD_PREV"),ordered = TRUE)

## Oral


l = list()

for (cond in unique (df_AIM$Condition_merged, ordered = T)) {
  
  df_oral = df_AIM %>% 
    filter(time != "-20") %>% 
    filter(Condition_merged == cond)
  
  df_oral2 = data.frame(Condition = df_oral$Condition_merged,
                 Phase = df_oral$time,
                 Rate = df_oral$value_oral,
                 Week = df_oral$Week)
  
  g_oral = list()
  
  for(w in unique(df_AIM$Week)) {
    
    g_oral[[w]] <- ggplot(data=subset(df_oral2, Week == w),                        
                          aes(x = Phase, y = Rate, fill = Phase, color = Condition)) +
      #geom_boxplot(aes(middle  = median(Rate), color = Condition), width = .9, position = position_dodge2(padding=.7, width=0.7)) +
      geom_boxplot(aes(middle  = median(Rate), color = Condition), width = 0.3, position = position_dodge(0.9))  +
      theme_classic() +
      theme(legend.position="none") + 
      colScale+
      scale_fill_manual(values=c("#FFFFFF", "#FFFFFF", "#FFFFFF", "#FFFFFF",  "#FFFFFF",  "#FFFFFF",  "#FFFFFF"))+
      ylim(0,4)+
      scale_x_discrete(labels = c("0", " ", " ", "60", " ", " ", "120"))+
      labs(x="Time (min)", y = "Oral AIMs score")
  }
  
  g_oral = g_oral[-c(1, 2, 3)]
      
  l[[cond]] = do.call(grid.arrange, c(g_oral, ncol=6))
  l2 = l[c("SHAM", "PD", "PD_CORR", "PD_PREV")]
  
}

l_oral = do.call(grid.arrange, c(l2, nrow=4))
plot(l_oral)

#ggsave("Oral_AIM_Detailed_FigSupp1.pdf", l_oral, useDingbats= F, height = 8.2 , width = 6 * aspect_ratio)

write_xlsx(df_oral,"C:/Users/berenice/Documents/Src/Bérénice/FigSupp2b.xlsx")


### Limb 

l = list()

for (cond in unique (df_AIM$Condition_merged, ordered = T)) {
  
  df_limb = df_AIM %>% 
    filter(time != "-20") %>% 
    filter(Condition_merged == cond)
  
  df_limb2 = data.frame(Condition = df_limb$Condition_merged,
                 Phase = df_limb$time,
                 Rate = df_limb$value_limb,
                 Week = df_limb$Week)
  
  g_limb = list()
  
  for(w in unique(df_AIM$Week)) {
    
    g_limb[[w]] <- ggplot(data=subset(df_limb2, Week == w),                        
                          aes(x = Phase, y = Rate, fill = Phase, color = Condition)) +
      #geom_boxplot(aes(middle  = median(Rate), color = Condition), width = .9, position = position_dodge2(padding=.7, width=0.7)) +
      geom_boxplot(aes(middle  = median(Rate), color = Condition), width = 0.3, position = position_dodge(0.9))  +
      theme_classic() +
      theme(legend.position="none") + 
      colScale+
      scale_fill_manual(values=c("#FFFFFF", "#FFFFFF", "#FFFFFF", "#FFFFFF",  "#FFFFFF",  "#FFFFFF",  "#FFFFFF"))+
      ylim(0,4)+
      scale_x_discrete(labels = c("0", " ", " ", "60", " ", " ", "120"))+
      labs(x="Time (min)", y = "Limb LID score")
  }
  
  g_limb = g_limb[-c(1, 2, 3)]
      
  l[[cond]] = do.call(grid.arrange, c(g_limb, ncol=6))
  l2 = l[c("SHAM", "PD", "PD_CORR", "PD_PREV")]
  
}

l_limb = do.call(grid.arrange, c(l2, nrow=4))
plot(l_limb)

#ggsave("Limb_AIM_Detailed_BP_FigSupp1-V3.pdf", l_limb, useDingbats= F, height = 8.2 , width = 6 * aspect_ratio)


### Axial

l = list()

for (cond in unique (df_AIM$Condition_merged, ordered = T)) {
  
  df_axial = df_AIM %>% 
    filter(time != "-20") %>% 
    filter(Condition_merged == cond)
  
  df_axial2 = data.frame(Condition = df_axial$Condition_merged,
                 Phase = df_axial$time,
                 Rate = df_axial$value_axial,
                 Week = df_axial$Week)
  
  g_axial = list()
  
  for(w in unique(df_AIM$Week)) {
    
    g_axial[[w]] <- ggplot(data=subset(df_axial2, Week == w),                        
                          aes(x = Phase, y = Rate, fill = Phase, color = Condition)) +
      geom_boxplot(aes(middle  = median(Rate), color = Condition), width = 0.3, position = position_dodge(0.9))  +
      theme_classic() +
      theme(legend.position="none") + 
      colScale+
      scale_fill_manual(values=c("#FFFFFF", "#FFFFFF", "#FFFFFF", "#FFFFFF",  "#FFFFFF",  "#FFFFFF",  "#FFFFFF"))+
      ylim(0,4)+
      scale_x_discrete(labels = c("0", " ", " ", "60", " ", " ", "120"))+
      labs(x="Time (min)", y = "Limb LID score")
  }
  
  g_axial = g_axial[-c(1, 2, 3)]
      
  l[[cond]] = do.call(grid.arrange, c(g_axial, ncol=6))
  l2 = l[c("SHAM", "PD", "PD_CORR", "PD_PREV")]
  
}

l_axial = do.call(grid.arrange, c(l2, nrow=4))
plot(l_axial)

#ggsave("axial_AIM_Detailed_BP_FigSupp1-V3.pdf", l_axial, useDingbats= F, height = 8.2 , width = 6 * aspect_ratio)


```



#####
##### Figure Supp 2c - OFF period AIM - BP
#####

```{r}

df_oral = df_AIM %>% 
    filter(time == "-20")
  
df_oral2 = data.frame(Condition = df_oral$Condition_merged,
                      Phase = df_oral$time,
                      Rate = df_oral$value_oral,
                      Week = df_oral$Week)

df_oral2$Week <- factor(df_oral2$Week,
                          levels = c("4", "5", "6", "7", "8", "9"),ordered = TRUE)

g_oral = list()

for (cond in unique (df_AIM$Condition_merged)) {  
  
  g_oral[[cond]] <- ggplot(data=subset(na.omit(df_oral2), Condition == cond),                        
                        aes(x = Week, y = Rate, fill = Week, color = Condition)) +
    geom_boxplot(aes(middle  = median(Rate)), width = 0.3, position = position_dodge(0.9))  +
    theme_classic() +
    theme(legend.position="none") + 
    colScale+
    scale_fill_manual(values=c("#FFFFFF", "#FFFFFF", "#FFFFFF", "#FFFFFF",  "#FFFFFF",  "#FFFFFF"))+
    ylim(0,4)+
    labs(x="Weeks", y = "Oral off-period AIMs score")
  
}

l2=g_oral[c("SHAM", "PD", "PD_CORR", "PD_PREV")]
#names(l2) = c("SHAM", "DYSKINETIC", "CORRECTIF", "PREVENTIF")
p = do.call(grid.arrange, c(l2, ncol=4))
plot(p)
  
#ggsave("Oral_offperiod_BP_FigS1_V3.pdf", p, useDingbats= F, height = 5 , width = 5 * aspect_ratio)

write_xlsx(df_oral2,"C:/Users/berenice/Documents/Src/Bérénice/FigSupp2c.xlsx")

```


#####
##### Figure Supp 5 - All AIMs SHAM - BP
#####


```{r}
## Oral

df = df_AIM %>% filter(Condition_merged == "SHAM")

df_AIM$Condition_merged <- factor(df_AIM$Condition_merged,
    levels = c("SHAM", "PD", "PD_CORR", "PD_PREV"),ordered = TRUE)

df_oral_sham = aggregate(value_oral~Week*Condition*mouse, data = df, FUN=function(x) sum(x))

df_oral_sham$Week <- factor(df_oral_sham$Week,
                      levels = c("4", "5", "6", "7", "8", "9"),ordered = TRUE)

  p1 <- ggplot(data=df_oral_sham, aes(x = Condition, y = value_oral, fill = Week, color = Condition)) +
    geom_boxplot(aes(middle  = mean(value_oral)), width = .9, position = position_dodge2(padding=.7, width=0.7))+
    theme_classic()+
    theme(legend.position = "none",
          axis.text.x = element_text(size = 18, angle = 0, hjust = .5, vjust = .5, face = "plain"),
          axis.text.y = element_text(size = 18),
          axis.title.x = element_text(size = 20, angle = 0, hjust = .5, vjust = 0, face = "plain"),
          axis.title.y = element_text(size = 20, angle = 90, hjust = .5, vjust = .5, face = "plain"))+
    ylim(0,2)+
    scale_fill_manual(values=c("#FFFFFF", "#FFFFFF", "#FFFFFF", "#FFFFFF", "#FFFFFF", "#FFFFFF"))+
    scale_color_grey()+
    labs(x="Weeks", y = "Total oral AIMs score in SHAM")

plot(p1)

write_xlsx(df,"C:/Users/berenice/Documents/Src/Bérénice/FigSupp5.xlsx")
```


#####
##### FigSupp8 - Diff ON/OFF in SHAM - BP
#####


```{r}

df = df_all_s053 %>% 
  filter(block == 3 & Phase == "Pre-LDOPA" | block == 7 & Phase == "Post-LDOPA") %>% 
  filter(quality <= 2) %>% 
  filter(Week_cat5 != "W1") %>% 
  filter(Condition_merged == "SHAM") %>% 
  dplyr::select("Week2", "mouse", "Condition", "Condition_merged", "region2", "region","name", "cell", "rate", "quality", "mouse", "cell", "Week_cat5", "rate", "FRon", "FRoff")


### FR ALL

df2 = data.frame(Condition = df$Condition,
                 Phase = df$Week_cat5,
                 Rate = df$rate, 
                 region2 = df$region2)

g = list()

for(reg in unique(df$region2)) {
  g[[reg]] <- ggplot(data=subset(df2, reg == region2), aes(x = Condition, y = Rate, Fill = Phase, color = Condition)) +
    geom_boxplot(aes(middle  = mean(Rate)), width = .9, position = position_dodge2(padding=.7, width=0.7))+
    theme_classic()+
    theme(legend.position="none",
          plot.title = element_text(size=20),
          axis.text.x = element_text(size = 18, angle = 0, hjust = .9, vjust = .9, face = "plain"),
          axis.text.y = element_text(size = 18),  
          axis.title.x = element_text(size = 20, angle = 0, hjust = .5, vjust = 0, face = "plain"),
          axis.title.y = element_text(size = 20, angle = 90, hjust = .5, vjust = .5, face = "plain"))+
    ylim(0,51)+
    scale_fill_manual(values=c("#FFFFFF", "#FFFFFF", "#FFFFFF", "#FFFFFF", "#FFFFFF", "#FFFFFF"))+
    scale_color_grey()+
    labs(title= paste(print(reg)), 
         x="Weeks", y = "Rate (Hz)")
  #print(g)
}

f = do.call(grid.arrange,c(g, ncol=3))
plot(f)

#ggsave("FR_ALL_SHAMnostim_separated_FigSupp4-V3.pdf", f, height = 5 , width = 4 * aspect_ratio)

write_xlsx(df2,"C:/Users/berenice/Documents/Src/Bérénice/FigSupp8b_Left.xlsx")

### FR_ON


df2 = data.frame(Condition = df$Condition,
                 Phase = df$Week_cat5,
                 FRon = df$FRon, 
                 region2 = df$region2)

g1 = list()

for(reg in unique(df$region2)) {
  g1[[reg]] <- ggplot(data=subset(df2, reg == region2), aes(x = Condition, y = Rate, Fill = Phase, color = Condition)) +
    geom_boxplot(aes(middle  = mean(Rate)), width = .9, position = position_dodge2(padding=.7, width=0.7))+
    theme_classic()+
    theme(legend.position="none",
          plot.title = element_text(size=20),
            axis.text.x = element_text(size = 18, angle = 0, hjust = .9, vjust = .9, face = "plain"),
        axis.text.y = element_text(size = 18),  
        axis.title.x = element_text(size = 20, angle = 0, hjust = .5, vjust = 0, face = "plain"),
        axis.title.y = element_text(size = 20, angle = 90, hjust = .5, vjust = .5, face = "plain"))+
    ylim(0,51)+
    scale_fill_manual(values=c("#FFFFFF", "#FFFFFF", "#FFFFFF", "#FFFFFF", "#FFFFFF", "#FFFFFF"))+
    scale_color_grey()+
    labs(title= paste("FR_ON", print(reg)), 
         x="Weeks", y = "Rate during locomotor activity (Hz)")
  #print(g)
}

f1 = do.call(grid.arrange,c(g1, ncol=3))
plot(f1)

write_xlsx(df2,"C:/Users/berenice/Documents/Src/Bérénice/FigSupp8b_Middle.xlsx")


### FR_OFF

df2 = data.frame(Condition = df$Condition,
                 Phase = df$Week_cat5,
                 FRoff = df$FRoff, 
                 region2 = df$region2)

g2 = list()

for(reg in unique(df$region2)) {
  g2[[reg]] <- ggplot(data=subset(df2, reg == region2), aes(x = Condition, y = Rate, Fill = Phase, color = Condition)) +
    geom_boxplot(aes(middle  = mean(Rate)), width = .9, position = position_dodge2(padding=.7, width=0.7))+
    theme_classic()+
    theme(legend.position="none",
          plot.title = element_text(size=20),
            axis.text.x = element_text(size = 18, angle = 0, hjust = .9, vjust = .9, face = "plain"),
        axis.text.y = element_text(size = 18),  
        axis.title.x = element_text(size = 20, angle = 0, hjust = .5, vjust = 0, face = "plain"),
        axis.title.y = element_text(size = 20, angle = 90, hjust = .5, vjust = .5, face = "plain"))+
    ylim(0,51)+
    scale_fill_manual(values=c("#FFFFFF", "#FFFFFF", "#FFFFFF", "#FFFFFF", "#FFFFFF", "#FFFFFF"))+
    scale_color_grey()+
    labs(title= paste("FR_OFF", print(reg)), 
         x="Weeks", y = "Rate during locomotor inactivity (Hz)")
  #print(g)
}
f2 = do.call(grid.arrange,c(g2, ncol=3))
plot(f2)

#write_xlsx(df2,"C:/Users/berenice/Documents/Src/Bérénice/FigSupp8b_Right.xlsx")

f3 = do.call(grid.arrange, c(g, g1, g2, nrow=3))
plot(f3)

#ggsave("FR_ALL-ON-OFF_SHAMdiff_FigSupp4-V3.pdf", f3, useDingbats= F,height = 7 , width = 4 * aspect_ratio)


### Test de levene - variance

df_stat = df
df_stat$log.rate = log(df$rate)
df_stat$Week_cat5 <- factor(df_stat$Week_cat5, levels = c("W1", "W2-W3", "W4-W5", "W6-W7", "W8-W9"),ordered = TRUE)
df_stat = df_stat %>% filter(Condition %in% c("SHAM", "SHAM_PREV"))

g1_levene = list()
g2_levene = list()

for (reg in unique(df_stat$region)) {
  for (cond in unique(df_stat$Condition)) {
  s = subset(df_stat, region == reg & Condition == cond)
  s2 = s %>% filter(Week_cat5 != "W1") %>% dplyr::select ("Condition", "Week_cat5", "FRoff")
  s2$Week_cat5 = droplevels(s2$Week_cat5)
  s2$Condition = droplevels(s2$Condition)
  l = leveneTest(FRoff~Week_cat5, data = na.omit(s2))
  g1_levene[[cond]] = l$`Pr(>F)`
  #print(paste(reg,cond, l$`Pr(>F)`))
  }
g2_levene[[reg]] = g1_levene
  }

g3_anova = list()
g3_welch = list()
g4_anova =list()
g4_welch =list()

for (reg in unique(df_stat$region)) {
  for (cond in unique(df_stat$Condition)) {
    s = subset(df_stat, region == reg & Condition == cond)
    s2 = s %>% filter(Week_cat5 != "W1") %>% dplyr::select ("Condition", "Week_cat5", "FRoff")
    s2 = na.omit(s2)
    s2$Week_cat5 = droplevels(s2$Week_cat5)
    s2$Condition = droplevels(s2$Condition)
    print(cond)
    if (g2_levene[[reg]][[cond]][[1]] > 0.05) {
      res.avo = aov(FRoff~Week_cat5, data = na.omit(s2))
      summary(res.avo)
      g3_anova[[cond]] = TukeyHSD(res.avo)
      #$Week_cat5[,4]
      paste(print(reg), print(cond))
   
       } else {
      #welch_res = welch.test(log.rate~Week_cat5, data=na.omit(s2))
      #p = posthocTGH(s2$log.rate, s2$Week_cat5, method="games-howell", conf.level = 0.95, digits=5)
      welch_res = welch.test(FRoff~Week_cat5, data=na.omit(s2))
      p = posthocTGH(s2$FRoff, s2$Week_cat5, method="games-howell", conf.level = 0.95, digits=5)
      g3_welch[[cond]] = p$output$games.howell
  }
  }
  g4_anova[[reg]] = g3_anova
  g4_welch[[reg]] = g3_welch
}

#g4_anova[[1]][[1]]$Week_cat5[,4]

#### Mean + n 

m=list()
nb=list()
m2=list()
nb2=list()
m3=list()
nb3=list()
nb_mouse=list()
nb_mouse2=list()
nb_mouse3=list()

for (reg in unique(df_stat$region)) {
  for (cond in unique(df_stat$Condition)) {
    for (w in unique(df_stat$Week_cat5)) {
      s = df_stat %>% filter(Week_cat5 != "W1")  %>% dplyr::select ("Condition", "Week_cat5", "FRoff", "region", "mouse", "name")
      s2 = subset(s, region == reg & Condition == cond & Week_cat5 == w)
      s2=na.omit(s2)
      m[[w]] = mean(s2$FRoff)
      paste(print(w), print(cond), print(reg))
      nb[[w]] = length(s2$name)
      nb_mouse[[w]] = length(unique(s2$mouse))
    }
    m2[[cond]] = m
    nb2[[cond]] = nb
    nb_mouse2[[cond]] = nb_mouse
  }
  m3[[reg]] = m2
  nb3[[reg]] = nb2
  nb_mouse3[[reg]] = nb_mouse2
}
```



#####
##### FigSupp9 - BurstRate ON/OFF - BP
#####


```{r}

### ON 

df = df_all_s053 %>% 
  filter(block == 3 & Phase == "Pre-LDOPA" | block == 7 & Phase == "Post-LDOPA") %>% 
  filter(quality <= 2) %>% 
  filter(Week_cat5 != "W1") %>% 
  filter(Condition %in% c("SHAM", "PD", "PD_PREV")) %>% 
  dplyr::select("Week_cat5", "mouse", "Condition_merged", "region2", "b.rate", "b.rate.on", "b.rate.off")

df2 = data.frame(Condition = df$Condition,
                 Phase = df$Week_cat5,
                 BurstON = df$b.rate.on, 
                 region2 = df$region2)

g = list()

for(reg in unique(df2$region2)) {
  g[[reg]] <- ggplot(data=subset(df2, reg == region2), aes(x = Condition, y = BurstON, Fill = Phase, color = Condition)) +
    geom_boxplot(aes(middle  = mean(BurstON)), width = .9, position = position_dodge2(padding=.7, width=0.7))+
    theme_classic()+
    theme_classic()+
    theme(legend.position="none")+
    theme(legend.position="none",
           plot.title = element_text(size=20),
           axis.text.x = element_text(size = 18, angle = 0, hjust = .5, vjust = .5, face = "plain"),
           axis.text.y = element_text(size = 18),  
           axis.title.x = element_text(size = 20, angle = 0, hjust = .5, vjust = 0, face = "plain"),
           axis.title.y = element_text(size = 20, angle = 90, hjust = .5, vjust = .5, face = "plain"))+
    scale_y_continuous(
    labels = scales::number_format(accuracy = 0.1))+
    #ylim(0,3.4)+
    colScale+
    #shapeScale+
    labs(title= paste(print(reg)), 
         x="Weeks", y = "Burst Rate (Hz)")
  #print(g)
}

f = do.call(grid.arrange,c(g, ncol=3))
plot(f)


ggsave("Burst.rate-Fig2.V4.pdf", f, height = 4 , width = 4 * aspect_ratio)

write_xlsx(df2,"C:/Users/berenice/Documents/Src/Bérénice/FigSupp9a.xlsx")


### OFF


df2 = data.frame(Condition = df$Condition,
                 Phase = df$Week_cat5,
                 BurstOFF = df$b.rate.off, 
                 region2 = df$region2)

g = list()

for(reg in unique(df2$region2)) {
  g[[reg]] <- ggplot(data=subset(df2, reg == region2), aes(x = Condition, y = BurstOFF, Fill = Phase, color = Condition)) +
    geom_boxplot(aes(middle  = mean(BurstOFF)), width = .9, position = position_dodge2(padding=.7, width=0.7))+
    theme_classic()+
    theme(legend.position="none",
          plot.title = element_text(size=20),
          axis.text.x = element_text(size = 18, angle = 0, hjust = .5, vjust = .5, face = "plain"),
          axis.text.y = element_text(size = 18),  
          axis.title.x = element_text(size = 20, angle = 0, hjust = .5, vjust = 0, face = "plain"),
          axis.title.y = element_text(size = 20, angle = 90, hjust = .5, vjust = .5, face = "plain"))+
    colScale+
    ylim(0,15)+
    labs(title= paste(print(reg)), 
         x="Weeks", y = "Burst Rate during locomotor inactivity (Hz)")
  #print(g)
}
f = do.call(grid.arrange,c(g, ncol=3))
plot(f)


ggsave("FigSupp5-V3_Burst.rate.off.pdf", f, useDingbats= F, height = 4 , width = 4 * aspect_ratio)

write_xlsx(df2,"C:/Users/berenice/Documents/Src/Bérénice/FigSupp9b.xlsx")


```














